sudo: false
language: python
cache: python

env:
    matrix:
        - TOX_ENV=py26
        - TOX_ENV=py27
        - TOX_ENV=pypy
        - TOX_ENV=py34

matrix:
    fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
